data_file = "public/data.json"
public_dir = "public"
qr_dir = "public/qr"

[verifier]
name = "Local Metadata Signer"
public_key = "ee6a7cd8146e9f02e4ae9f59908a5b513186e786696c6afe9644ff59bdbdbe7c"

[[chains]]
name = "node-subtensor"
rpc_endpoint = "wss://archivelb.nakamoto.opentensor.ai:9943"
color = "#000000"

[chains.github_release]
owner = "opentensor"
repo = "subtensor"
genesis_hash = "0xadcb639cec07168f455d8bd3a43badf1114a414836829f5000e8279f70d4c667"