runs:
  using: "composite"
  steps:
    - name: 🔨 Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y clang libclang-dev libopencv-dev
      shell: bash

    - name: 🔧 Install stable toolchain
      uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f
      with:
        profile: minimal
        toolchain: stable
        components: clippy, rustfmt

    - name: 💾 Rust Cache
      uses: Swatinem/rust-cache@v2
